### ISSUE TITLE
Paths with dots produce 500

### ISSUE THREAD

**Issue by rofe** [adobe/helix-pages#218]
Example: https://{yourrepo}-{yourorg}.hlx.page/.bla.html

Expected result: 200 or 404

Actual result: 500

**Comment by kptdobe** [comment]
I can look at it but I cannot promise it will not trigger escalations ;)

**Comment by kptdobe** [comment]
dispatch responds 403, it is our error handling in Fastly which triggers the 500.

**Comment by rofe** [comment]
Interesting: why 403 instead of 404?

**Comment by kptdobe** [comment]
Actually, it is the `forbidden` response from helix-static which is then transformed into a 500 at Fastly level...

https://github.com/adobe/helix-static/blob/master/src/index.js#L460

The `blacklisted` method should not properly handle this "undesirable" path case. 

https://github.com/adobe/helix-static/blame/master/src/index.js#L394

I think the fix should be in this `blacklist` function so that static would return a 404.

On the other hand, when someone will try to access a really blacklisted resource, we would fire a 500 which I think is not better neither. Maybe dispatch should respond 404 in case of one of the fetcher would return 403.

2 options:
1. `helix-static` `blacklist` function should handle better this special path case
2. 'helix-dispatch` should hide 403 from fetchers and respond 404.

@trieloff @rofe @tripodsan WDYT ?

I vote for 2 so that we hide some internal logic. Since static would still return 403, via the logs, we can still find out that someone tried to access a forbidden resource.

**Comment by kptdobe** [comment]
Option 3: change fastly to not report a 500 in case of 403. But I do not think exposing a 403 here is better.

**Comment by rofe** [comment]
My vote goes to option 2 as well.

**Comment by trieloff** [comment]
I think that the 403 from static is accurate, if inconvenient and scary to the visitor. But come on, what should a visitor expect that is trying to sniff around in our `.env` files?

Fastly should pass through the 403, of course. Maybe even with a delay, so that bots learn to scan other sites instead.

**Comment by stefan-guggisberg** [comment]
The current implementation forbids any path element with a leading `.`. This seems reasonable.

-> Option 2: don't propagate `403`s

**Comment by stefan-guggisberg** [comment]
Hmm, changed my mind. I am with Lars. 

=> Option 3: Let Fastly propagate `403`s, among others, e.g. `504`s.

**Comment by rofe** [comment]
OK, option 3 it is for me as well 😃

**Comment by kptdobe** [comment]
With https://github.com/adobe/helix-publish/issues/378, paths with dots now trigger 403: https://theblog--adobe.hlx.page/.bla.html
