### ISSUE TITLE
fetch whitelist from iframely

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-pages#269]
fetch whitelist from http://iframe.ly/domains.json and construct embed-whitelist to meet specific needs for helix-pages! 

fixes: 
https://github.com/adobe/helix-embed/issues/218
https://github.com/adobe/helix-pipeline/issues/701
https://github.com/adobe/helix-pipeline/issues/702
https://github.com/adobe/helix-pipeline/issues/700
 4 birds one stone....helix style :)

**Comment by kptdobe** [comment]
I would make this a manual process, i.e. download the file and put it somewhere in the pipeline:
- the change ratio should not be too frequent
- I assume that existing services do not remove their embed urls from the list of a daily basis
- I think we need to be aware of the changes because this may have an impact on the content... if `youtube` embeds change, we need to update a lot of content pages
- if a new service is introduced and someone wants to use it, this would be the trigger to update the list...

**Comment by trieloff** [comment]
This will take some additional work in `helix-pipeline`. The embed whitelist is currently domain-based and uses globbing, the iframely whitelist uses regular expressions on the entire domain. We would need a new parameter that can take an array of regular expressions, which takes precedence over the existing whitelist.

Then we can implement what @kptdobe suggested: have a small build script that runs at deploy time for Helix Pages which pulls the JSON file, converts it into a list of regular expressions and passes it as a parameter into the pipeline.

Other than Alex I think an automated update is fine, which gives us the advantage that new services are supported immediately and without any intervention. Otherwise we can keep the current approach of whitelisting in helix-pipeline on demand.

**Comment by kptdobe** [comment]
I am not against "automation", I am just worried that it becomes an extra request at runtime ;)
Autoupdate pre-release is fine too :)

**Comment by davidnuescheler** [comment]
i think it seems a little bit of a very large list, or at least when i looked through it, it felt like there was a large long tail of external embeds that are probably never going to be used in most cases. it reminds me of an endless mime-type list with 99% of filetypes that nobody has ever heard of... 

i think this may be useful for sites where generic embedding is needed, but i think that most (enterprise) customers will want to be fairly selective white listing embed sources...

**Comment by trieloff** [comment]
Fully agree, but that's why I suggested to open the issue in `helix-pages`, where we can live with being permissive rather than `helix-pipeline` which sets the default for our enterprise users and should only include providers that we have tested ourselves.
