### ISSUE TITLE
Include Twitter metadata tags by default

### ISSUE THREAD

**Issue by rofe** [adobe/helix-pages#272]
Twitter doesn't seem to care about Open Graph (see #261), so we need to include `twitter.*` meta tags for nicer rendering when sharing links.

**Comment by rofe** [comment]
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup

**Comment by davidnuescheler** [comment]
i just tried out twitter and still didn't get any preview image...

also, shouldn't the `og:image`, `og:image:secure_url` `twitter:image` point to a `/hlx_` url instead of  `https://hlx.blob.core.windows.net/external/` 
...also it looks like the recommended image size is 1200:630, which could be an opportunity to use `?width=1200` or similar... i am not sure if that supports a `cover` style image crop...

**Comment by rofe** [comment]
> i just tried out twitter and still didn't get any preview image...

Weird, what URL did you try? Note that you have to stay on the `metadata` branch for Blog URLs as long as https://github.com/adobe/theblog/pull/180 is not merged yet (review welcome 😉) otherwise twitterbot will not be allowed in. I tried https://metadata--theblog--adobe.hlx.page/en/drafts/migrated/2020/04/27/the-state-of-utah-uses-adobe-sign-to-accelerate-telework-during-crisis.html and it worked: https://twitter.com/_Maloney___/status/1258748036374806528?s=20

> also, shouldn't the `og:image`, `og:image:secure_url` `twitter:image` point to a `/hlx_`

Yes, it should. This should be handled in the pipeline. I had created https://github.com/adobe/helix-pipeline/issues/706 for it.

**Comment by rofe** [comment]
Just retried after merging the `metadata` branch, worked as expected:
https://twitter.com/_Maloney___/status/1259767823913680897?s=20
