### ISSUE TITLE
Image captions

### ISSUE THREAD

**Issue by rofe** [adobe/helix-pages#299]
We currently don't have special handling for image captions, so they are rendered like normal text paragraphs. I think it would be nice if we had a way to detect captions and add a class to their <p> so they can be styled differently.

Image captions are typically (but not always) short paragraph texts that follow images directly, but distinguishing them from normal text isn't exactly straight forward. 

Some examples:
> Photo by Adobe Stock / Foo.
> Image by Foo Bar.
> Image source: Foo Bar.
> Image source: Adobe Stock / Foo / Bar.
> Adobe Stock Image: Gender equality.
> Adobe For All: Advancing inclusion for people of all backgrounds.
> Left: 30 years of Foo. Right: Lorem ipsum dolor sit amet

So maybe we might look for text paragraphs that directly follow image paragraphs and any of the following:
- are short(ish) and start with "Image", "Photo(graph)"
- contain Adobe Stock (or other common stock libraries)
- contain a colon?

**Comment by davidnuescheler** [comment]
i actually think that this usecase may be more relevant for news / articles than general purpose web sites... so i think we can implement something like this on theblog (and i think we could do it client sided) before hoisting this into helix pages.

looking at the blog in particular, it turns out that people have been very creative with the styling of their image legends, and they are in fact not all `p` but some of them are smaller sized headings :(
