### ISSUE TITLE
add performance testing to pages.test.js

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-pages#388]
There should be a way to continuously test how page performance is effected by a branch and to notify Helix developers when this change is negative!

Ideas: 
1) test against lighthouse score @trieloff 
2) test against pipeline rendering time as reporting performance loss from things we cannot control at the branch level is pointless. @davidnuescheler 

It seems we agreed on 2. @rofe anything you'd like to add on the subject?

**Comment by trieloff** [comment]
There are two things here:

1. Picking the correct baseline
2. Picking the correct measure

1. If we compare the branch build against the master build (both on inner CDN) we will minimize the risk of contamination due to factors out of our control.
2. Using the Calibre CLI (or helix-perf) gives us a number of metrics we can compare. Should lighthouse score alone be too much a reflection of CDN cache settings then we can pick a different one. Pipeline rendering time alone is probably not sufficient as it hides the impact of everything that’s outside the pipeline.

**Comment by MarquiseRosier** [comment]
Right, helix-perf it is. Right; caching will definitely contaminate the results here. Does helix-perf account for innercdn here or will we have to hit uncached version of helix pages? @trieloff

**Comment by trieloff** [comment]
Helix-perf takes a list of URLs as input from helix-config.yaml - it doesn’t care for inner our outer CDN. All the URLs we get from Google are inner CDN anyway.

Helix-perf compares against threshold values, it does not have the ability to compare against a baseline yet.

**Comment by MarquiseRosier** [comment]
@trieloff ok! Thanks for these pointers; i'll open an issue to support comparing against a baseline right now!
