### ISSUE TITLE
Default CSS styling broken

### ISSUE THREAD

**Issue by rofe** [adobe/helix-pages#493]
The current default styles rely on decorator classes which are no longer present since #403.

**Comment by kptdobe** [comment]
@davidnuescheler said yesterday he will take care of a new default styling for helix-pages.

**Comment by rofe** [comment]
Yes, this is meant as an intermediate solution to un-break existing sites using the default styling (e.g. `helix-home`).

**Comment by davidnuescheler** [comment]
well, it is primarily to unbreak the ootb experience for helix pages, but yes visually unbreaking some existing sites with an unmodified `head.html` would also be nice...

**Comment by davidnuescheler** [comment]
first draft in new-styling branch... for some weird reason i cannot look at it at https://styling-update--helix-pages--adobe.hlx.page/ but local clone should work.

supports darkmode preference and is very minimal on purpose...

**Comment by rofe** [comment]
This issue's original purpose was to fix the bug that the current default styling is broken ootb due to the missing default decorations. I would suggest to create a dedicated enhancement issue for the new styling.

**Comment by rofe** [comment]
@davidnuescheler and I decided we won't fix the broken old design, but rather introduce the new one instead.

**Comment by kptdobe** [comment]
> i cannot look at it at https://styling-update--helix-pages--adobe.hlx.page/ but local clone should work.

Took me a while to find an explanation but... you cannot because: the "override" mechanism will look for `/head.html` in content repository at the root, not under `/htdocs`. Your branch ` styling-update` is the content repository thus to use the override mechanism from helix-pages, you need to move the head, styles and scripts files at the root.

Here is a working version: https://styling-update-tmp--helix-pages--adobe.hlx.page/ (I just moved the files at the root)
But since we are finally changing "helix-pages", we do not want this. This is an edge case.
