### ISSUE TITLE
Sidekick: make fully compliant with helix-pages url scheme

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pages#596]
`https://{repo}-{owner}.hlx.page/` is equivalent to `https://{ref}--{repo}--{owner}.hlx.page/` thus a Sidekick config like the one below should recognise both the same way:

```
{
  owner: '{owner}',
  repo: '{repo}',
  ref: '{ref}
}
```

This is a real pain point for our users.

cc @rofe

**Comment by rofe** [comment]
I agree with @davidnuescheler that we should discontinue the single dash URL, or at least openly redirect it to the double dash URL. It just complicates things unnecessarily, without a real benefit for the user (not to mention the confusion). 

What's more, we don't use it as backend in the outer CDN, which means we also don't purge it with helix-purge... I remember SharePoint access being down, and our monitoring didn't catch it for 8h because it was looking at the single dash URL instead of the double dash one...

**Comment by rofe** [comment]
After discussing with @kptdobe, I'm withdrawing my veto and agree that the internal single to double dash conversion as he proposed.
