### ISSUE TITLE
[sidekick] purge on `.live` domains seems to fail due to CORS setup

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-pages#611]
currently there seems to be an issue for site that leverage the `.live` domain when publishing from `.page` preview, the purge doesn't happen as expected. conversely a publish directly from the `.live` domain works fine.

**Comment by rofe** [comment]
For a resource to be "published", the Sidekick Publish action must purge inner CDN, outer CDN and production host (if configured). Since it doesn't know if a project has an outer CDN set up, it probes the `.live` URL before sending that host name to `helix-purge` which otherwise would throw an error. The outer CDN doesn't currently allow requests from the inner CDN, though, which is why the Sidekick Publish action only works from the `.live` or production URL. 

I can see two solutions:

### CORS headers
Add an `Access-Control-Allow-Origin: https://<repo>--<owner>.hlx.page` response header to the outer CDN (can be restricted to origin inner CDN).

**Pro:**
- would enable client side requests from the inner to the outer CDN

**Con:**
- would add an additional step to the outer CDN setup

###  Assume outer CDN if production host set 
Remove the probing request from Sidekick Publish and simply assume that if there is a production host configured, there is also a outer CDN with `.live` host name, and purging of all 3 will work (if it failed, it would be due to a misconfigured setup). If there is no production host configured, only purge the inner CDN and ignore any outer CDN.

**Pro:**
- would not require CORS headers

**Con:**
- would not purge any outer CDN as long as no production host is provided, which could become inconvenient during the development phase of a project where no production host is defined yet, but devs still want to test on the cached `.live` domain.

**Comment by rofe** [comment]
@trieloff @stefan-guggisberg @asanso it would be great to have your input here as well.

I am leaning towards (1) because of its greater flexibility regarding the project setup. I've tried it out on `pages--adobe.hlx.live` and it fixes the underlying issue, hopefully without introducing any unexpected side effects:
```sh
curl -v -H "Origin: https://pages--adobe.hlx.page" https://pages--adobe.hlx.live/ 
```
returns `access-control-allow-origin: https://pages--adobe.hlx.page`, making it possible to send browser requests from `pages--adobe.hlx.page` to `pages--adobe.hlx.page`.

**Comment by trieloff** [comment]
1) we can probably add the Cors header on the inner CDN, trusting that it will be passed through all the way. This would eliminate one of your cons.

2) wouldn't sending a HLXPURGE request to the Skyline CDN be passed through all the way, accumulating the XFN header value?

**Comment by rofe** [comment]
1. If we don't mind it bubbling up to the Skyline CDN, that would be an option. Fwiw, I wanted to add it more conservatively, and even restricted to the `Origin` being the expected inner CDN.
2. Yes, it would. But if there is no Skyline CDN - in Sidekick config "production host (optional)" - defined yet, say during the evaluation or development phase, Sidekick Publish would only purge the inner CDN and the outer CDN, if one exists (hence the check via fetch)

**Comment by rofe** [comment]
After discussing with @davidnuescheler I will implement (2) 🙂 

He convinced me that it's OK to mandate a production/skyline host, but undesirable to complicate the outer CDN setup which might change again in the future.
