### ISSUE TITLE
style.css does not get pulled from content repo

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-pages#9]
adding a `style.css` to the content repo should override the `htdocs/style.css` in the `helix-pages` repo... 

see example here:
https://landing-davidnuescheler.project-helix.page/

and the content repo is here (of course):
https://github.com/davidnuescheler/landing

**Comment by rofe** [comment]
I think the content repo should have precedence by default. So for a `/bla.css` request it would look something like:
1. static fetch `/bla.css` from content repo
2. static fetch `/htdocs/bla.css` from code repo

For requests to extensions where we have a pipeline action, e.g. `/bla.html` we would prepend a request to the corresponding pipe, looking for a `/bla.md` in the content repo. If that turns out to be 404, we would go through the same static lookup sequence as above.

@tripodsan @trieloff wdyt?

**Comment by trieloff** [comment]
I don't think we should change the semantics and lookup order. The `content` repo will always get things from an action, and the `static` repo should always serve files. For Helix Pages, it might make sense to align `content` and `static` repo, which would create the behavior @rofe describes.

**Comment by rofe** [comment]
Whichever way we decide to go, let's make sure local dev and published site behave the same way.

**Comment by tripodsan** [comment]
we already have the special handling for images served from the content repo - we could also include `.css` and `.js`, since this seems to be a common use case.

**Comment by rofe** [comment]
> align `content` and `static` repo

if we pointed `static` at the content repo, it wouldn't fall back to the code repo, would it?

**Comment by kptdobe** [comment]
This should be resolved with: https://github.com/adobe/helix-publish/issues/96
To be validated once it is fixed.

**Comment by tripodsan** [comment]
I added some ugly workarounds for 
- html: https://github.com/adobe/helix-pages/commit/4ddc0d50257c031c2e881f0f553c6c1bb397481b
- css and js: https://github.com/adobe/helix-pages/commit/ee9801437c27a6cef8b7d373aa3feb229d40524a
